default:
  port: 8000
  width: 1440
  height: 1440
  fps: 30
  codec: libx264
  crf: 15
  input: input
  output: output
  saveImages: true
  saveVideo: true
  imageFilename: frame-#####
  videoFilename: video-##.mp4
  files:
    client.js:
      - common/*.js
      - client/vendor/*.js
      - client/classes/*.js
      - client/app.js
